### ISSUE TITLE
Free trade count is overwritten every time feedback is submitted.

### ISSUE THREAD

**Issue by BarDweller** [IBMStockTrader/portfolio#13]
This feels incorrect, everytime I post feedback, the number of free trades I have resets to the value associated with that feedback. 

So if I post angry feedback, and I'm granted 3 free trades, then post happy feedback, I'm reset to a single free trade, (which will probably make me angry, and submit more feedback).. 

Free trade count for feedback should probably be cumulative, and capped somehow to prevent abuse.

**Comment by jwalcorn** [comment]
Done.  Now it adds the new free trade count to the existing free trade count.

I haven't implemented a cap; ideally that would be temporal, like only one feedback per day or whatever.  But that would just be extra effort/complexity without much benefit at this point (it would probably mean adding a `lastFeedbackTimestamp` column to the Portfolio table, for example).
