### ISSUE TITLE
Refactor project to use packages 

### ISSUE THREAD

**Issue by BarDweller** [IBMStockTrader/portfolio#19]
As a starting suggestion,
 - clients
 - pojos/datamodel/model

And leave the main app where it is. 

Any sort of hierarchical grouping will vastly help people understand the codebase

**Comment by jwalcorn** [comment]
Done.  I put the JSON-B POJOs in a `json` subpackage, and the MP Rest Clients in a `client` subpackage.  I also added `stocktrader` to the package name, and then after that now comes the particular microservice name.  So now the main class is com.ibm.hybrid.cloud.sample.stocktrader.portfolio.PortfolioService.  Soon I'll do the same in the other repos, like putting Trader's Summary servlet at com.ibm.hybrid.cloud.sample.stocktrader.trader.Summary.  But for now, `portfolio` has been done.
