### ISSUE TITLE
Switch from raw JDBC to JPA

### ISSUE THREAD

**Issue by jwalcorn** [IBMStockTrader/portfolio#22]
Idea is to define a POJO with an `@Entity` annotation with a getter/setter for each column, per table (`Portfolio` and `Stock`).  Then `PortfolioService.java` would just call those accessor methods on the appropriate POJO to persist/retrieve data to/from the JDBC database (such as DB2).

Right now I'm doing things the way you would have 20 years ago - time to move up to something more modern (and to make the code a bit more similar to the Spring version).

There's a pretty good example here: http://www.vogella.com/tutorials/JavaPersistenceAPI/article.html

**Comment by yeekangc** [comment]
Open Liberty has a guide for JPA here: https://openliberty.io/guides/jpa-intro.html

**Comment by jwalcorn** [comment]
YK has graciously agreed to take this on.  He told me he's targeting a May delivery

**Comment by jwalcorn** [comment]
A PR was submitted for this today.  Initial review looks good.  Reviewing more thoroughly now...

**Comment by jwalcorn** [comment]
Merged that PR, after several suggestions and some extensive testing.  Thanks Andrew!
