### ISSUE TITLE
Event Stream secret to use service name

### ISSUE THREAD

**Issue by mossuchida** [IBMStockTrader/portfolio#28]
If Event Stream is deployed on ICP, service name should be used to access service stream.  For example:

kubectl create secret generic kafka -n stock-trader --from-literal=topic=stocktrader --from-literal=address=event-streams-trader-ibm-es-proxy-svc.event-streams.svc.cluster.local:30001 --from-literal=user=token --from-literal=api-key=<my key>

**Comment by jwalcorn** [comment]
We're not using IBM Event Streams anymore.  We do have the Kafka address exposed as a field in the CR yaml that our operator uses, so this really comes down to just putting the right hostname in the yaml - which could be a Kube DNS name, as suggested here, if the Kafka is running in your Kube cluster - though these days, we tend to use a Kafka-as-a-Service most of the time, such as MSK on AWS or Event Hubs on Azure (or a Confluent Cloud instance on confluent.io).
