### ISSUE TITLE
Need way to update certs.jks for Event Stream

### ISSUE THREAD

**Issue by mossuchida** [IBMStockTrader/portfolio#29]
Currently static certs.jks is used for Event Stream, however, it has to be replaced with own event stream topic certs.jks. Please provide alternate way to replace certs.jks.

**Comment by jwalcorn** [comment]
We should be able to use the "put the cert in an environment variable" approach that Liberty supports.  I haven't tried that with Event Streams, but it worked well with Redis.  See here: https://openliberty.io/blog/2019/12/06/microprofile-32-health-metrics-190012.html#ssl

**Comment by jwalcorn** [comment]
I'm going to assume the approach I pasted above solves this and close this out.  Of course, feel free to reopen if there's still any issue.  Thanks!
