### ISSUE TITLE
Please consider externalize these two hostname and port through a secret

### ISSUE THREAD

**Issue by vikramkhatri** [IBMStockTrader/portfolio#3]
https://github.com/IBMStockTrader/portfolio/blob/2fcc913fea6512f0dc859b1343a6dbd44d2ae301/src/main/java/com/ibm/hybrid/cloud/sample/portfolio/Portfolio.java#L75-L76

Hi John,

Please consider externalize these two host names and port through a secret object.

**Comment by jwalcorn** [comment]
Yeah, actually did this about a year ago in my umbrella helm chart, and last month in my OpenShift operator (that embeds the helm chart).

Stock Quote URL:
![image](https://user-images.githubusercontent.com/28963246/76247686-526e8a00-6216-11ea-9ebd-9f8e09f70b1b.png)

ODM URL (replaces old Loyalty URL - now an ODM business rule computes loyalty level):
![image](https://user-images.githubusercontent.com/28963246/76247865-9eb9ca00-6216-11ea-80b6-4f315e335b85.png)

Config map:
![image](https://user-images.githubusercontent.com/28963246/76247547-189d8380-6216-11ea-9d30-2a81e2b3b2f7.png)
