### ISSUE TITLE
Connection to MQ failed when MQ required a password for user app

### ISSUE THREAD

**Issue by brucexyz1234** [IBMStockTrader/portfolio#37]
The current stocktrader can connect to MQ which the MQ itself have no password configured for user app.

when trying to connecting to MQ which the MQ itself have a password configured for user app, it will be failed.

so, there might be a hardcoded/constrain  "BLANK" password for MQ in app stocktrader

so, we better ether :
1. ask user not to configure the MQ with password for user app, when installing MQ for stocktrader.
2. change the code of stocktrader to handle the password input from credential secret, to parse it and use it to connect to the target mq( either with specific value or blank, depending on actual case.

below is the MQ log when stocktrader connecting to a MQ which password setup for app user:
04/10/20 14:38:09 - Process(434.319) User(mqm) Program(amqrmppa)
                    Host(stocktrader-mq-ibm-mq-0) Installation(Installation1)
                    VRMF(9.1.5.0) QMgr(stocktradermq)
                    Time(2020-04-10T14:38:09.426Z)
                    RemoteHost(172.30.130.217)
                    CommentInsert1(jar)
                    CommentInsert2(172.30.130.217)
                    CommentInsert3(MCAUSER(app) CLNTUSER(default))
AMQ9791E: The client application did not supply a user ID and password.
EXPLANATION:
The client application 'jar' running on host '172.30.130.217' did not supply a
user ID and password. The channel authentication (CHLAUTH) record for the
connection requires a user ID and password, but none was supplied.
The active values of the channel were 'MCAUSER(app) CLNTUSER(default)'. The
MATCH(RUNCHECK) mode of the DISPLAY CHLAUTH MQSC command can be used to
identify the relevant CHLAUTH record.
ACTION:
Ensure that the application provides a valid user ID and password, or change
the queue manager connection authority (CONNAUTH) configuration to OPTIONAL to
allow client applications to connect which have not supplied a user ID and
password.

**Comment by brucexyz1234** [comment]
MQ_APP_PASSWORD - Changes the password of the app user. If set, this will cause the DEV.APP.SVRCONN channel to become secured and only allow connections that supply a valid userid and password. Must be at least 8 characters long.


above is the MQ_APP_PASSWORD  explaination

**Comment by jwalcorn** [comment]
My operator for installing Stock Trader now asks for the id and password needed to connect to MQ.  And the MQ installer now has you make a secret containing the "admin" password and the "app" password, so when you run the helm chart/operator for MQ and tell it the name of that secret, you end up knowing these credentials and just specify that when running my operator.  This has all been working for us, so I think this is addressed now and you won't end up with an "app" id with an empty password these days.  If there's still any issue here, feel free to reopen this with further details.  Thanks!
