### ISSUE TITLE
Kafka Authenticaion Mechanism for AWS differs from IBM Cloud

### ISSUE THREAD

**Issue by rtclauss** [IBMStockTrader/portfolio#46]
When using IBM EventStreams/Kafka the authentication mechanism is via username/password using the `PLAIN` SASL Mechanism.  This can be partially seen in [`EventStreamsProducer.java`](https://github.com/IBMStockTrader/portfolio/blob/014d14e/src/main/java/com/ibm/hybrid/cloud/sample/stocktrader/portfolio/EventStreamsProducer.java#L71-L72):
```java
...
        properties.put(SaslConfigs.SASL_MECHANISM, "PLAIN");
        properties.put(SaslConfigs.SASL_JAAS_CONFIG, "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"" + USERNAME + "\" password=\"" + API_KEY + "\";");
 ...       
```

However, Amazon MSK uses a different set of SASL mechanisms as outlined below:
```java
...
        properties.put(SaslConfigs.SASL_MECHANISM, "SCRAM-SHA-512");
        properties.put(SaslConfigs.SASL_JAAS_CONFIG, "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"" + USERNAME + "\" password=\"" + API_KEY + "\";");
...
```

[Azure Event Hubs](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs) can make use of the same, `PLAIN`, configuration or it can use `OAUTHBEARER` tokens with callback.

We need a generic mechanism to specify the SASL configuration for Kafka.

**Comment by rtclauss** [comment]
Related issue in [`trade-history`](https://github.com/IBMStockTrader/trade-history/issues/62)

**Comment by rtclauss** [comment]
Maybe make the SASL_MECHANISM and JAAS class environment variables/secrets?

**Comment by jwalcorn** [comment]
Fixed this several months ago
